<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <link rel="icon" href="images/nsc_small_logo.jpg" type="image/x-icon">
  <link rel="SHORTCUT ICON" href="images/nsc_small_logo.jpg" type="image/x-icon">
  <meta name="keywords" content="novel, new, start, codon, start-codon, startcodon, nsc, database">
  <meta name="description" content="Novel Start Codons database, a portal for the potential start codons in the human genomes">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>NSCDB - Novel Start Codon Databases @ QBRC, UTSW</title>
</head>
<body id='body_one'>
  <style>
  <?php include('nsc.css'); ?>
  </style>
  <div id='main_body'>

<?php
include('logo.inc');
include('menu.inc');
?>

<?php
include('dbconn.inc');
?>
