<table width="100%" height="100px">
  <tbody>
    <tr>
	    <!-- <td style="width: 200px" rowspan="2">
           <a href="/"><img src="images/title_pic.jpg" style="border: none; width: 280px" alt="PlantTFDB"></a>
           </td> -->
      <td style="vertical-align: center; padding-bottom: 5px;">
        <div class="logo_text">Novel Start Codons Database</div>
      </td>
    </tr>
  </tbody>
</table>
