<table width="100%" height="125px">
  <tbody>
    <tr>
	    <td style="width: 200px" rowspan="2">
        <a href="/"><img src="images/title_pic.jpg" style="border: none; width: 280px" alt="PlantTFDB"></a>
      </td>
      <td style="vertical-align: center; padding-bottom: 5px;">
        <div style="text-align: center; font-size: 2.3em;">Novel Start Codons Database</div>
      </td>
    </tr>
  </tbody>
</table>
