<table class="menu" height="30px">
  <tbody>
    <tr>
      <td style="width: 630px">
        <a href="/index.php">Home</a>
        &nbsp;&nbsp;
        <a href="/index.php">Search</a>
        &nbsp;&nbsp;
        <a href="/blast.php">Help</a>
      </td>
		
      <td style="width: 320px; text-align: right">
        <form method="post" action="quick_search_result.php" id="searchform" style="display: inline">
          <div style="text-align: right; padding-right: 0px">
             <input id="input_qsearch" name="input_qsearch" size="10" style="display: inline">
             <input name="submit_quick" type="submit" value="Search" style="display: inline; width: 53px"> (e.g., <a onclick="javascript: document.getElementById(&quot;input_qsearch&quot;).value=&quot;LFY&quot;">LFY</a>)
          </div>
        </form>
      </td>
    </tr>
  </tbody>
</table>
