<table class="menu" height="30px">
  <tbody>
    <tr>
      <td style="width: 480px">
        <a href="/index.php">Home</a>
        &nbsp;&nbsp;
        <a href="/up.php">Prediction</a>
        &nbsp;&nbsp;
        <a href="/help.php">Help</a>
      </td>
		
      <td style="width: 480px; text-align: right">
        <form method="get" action="list.php" id="searchform" style="display: inline">
          <div style="text-align: right; padding-right: 0px">
             <input id="input2" name="kw" size="20" style="display: inline">
             <input class="submit2" name="submit2" type="submit" value="Search" style="display: inline; width: 53px"> (e.g., <a onclick="javascript: document.getElementById('input_qsearch').value='CETP'">CETP</a>)
          </div>
        </form>
      </td>
    </tr>
  </tbody>
</table>
