<?php $conn->close(); ?>
<div class="footer">
  <hr>
  2020 &copy;&nbsp;
  <a href="https://qbrc.swmed.edu/" target="_blank">QBRC</a>&nbsp;&nbsp;|&nbsp;
  <a href="https://www.utsouthwestern.edu/departments/population-data-sciences/" target="_blank">Department of Population and Data Sciences</a>&nbsp;&nbsp;|&nbsp;
  <a href="http://www.utsouthwestern.edu/" target="_blank">UT Southwestern Medical Center</a>
</div>

</div>
</div>
</body>
</html>
