<?php $conn->close(); ?>
<div class="footer">
  <hr>
  <p>
    2020 &copy;&nbsp;
    <a href="https://qbrc.swmed.edu/" class="text-muted">QBRC &nbsp;&nbsp;| &nbsp;&nbsp;</a>
    <a href="https://www.utsouthwestern.edu/departments/population-data-sciences/" class="text-muted">Department of Population and Data Sciences &nbsp;&nbsp;| &nbsp;&nbsp;</a>
    <a href="http://www.utsouthwestern.edu/" class="text-muted">UT Southwestern Medical Center</a>
  </p>
</div>

</div>
</div>
</body>
</html>
